<a href="https://colab.research.google.com/github/JoseCarmona17/Bit-Data_Science/blob/main/Act_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad 5: Taller SQL (SQL Server)

Para completar el taller recuerda estas sentencias de SQL:

- DML (modifica datos):

  - INSERT: agrega filas a una tabla.
  - UPDATE: modifica columnas de filas existentes.
  - DELETE: elimina filas.
- SELECT (consulta datos):
  - SELECT: elige columnas a devolver (puede incluir expresiones).
  - WHERE: filtra filas (antes de agrupar).
  - GROUP BY: agrupa filas para usar agregados (SUM, COUNT, AVG, MIN, MAX).
  - HAVING: filtra grupos (después de GROUP BY).
  - ORDER BY: ordena el resultado.
  - TOP (N): limita la cantidad de filas devueltas (útil con ORDER BY).

*italicized text*## Conexion a BD

In [141]:
#Instala la libreria PyODBC
!pip install pyodbc

Requirement already satisfied: pyodbc in /usr/local/lib/python3.12/dist-packages (5.3.0)

In [142]:
import pyodbc
import pandas as pd

In [143]:
# Instalar dependencias y repositorio de Microsoft
!sudo su -c "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -"
!sudo su -c "curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list"
!sudo apt-get update
!sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100   975  100   975    0     0   7579      0 --:--:-- --:--:-- --:--:--  7617
OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    89  100    89    0     0   1009      0 --:--:-- --:--:-- --:--:--  1011
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unixodbc-dev is already the newest version (2.3.9-5ubuntu0.1).
msodbcsql17 is already the newest version (17.10.6.1-1).
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.

In [144]:
import pyodbc

# Parámetros de conexión
server = 'cdsc-bit.database.windows.net'
database = 'BDPruebasBIT'
username = 'TestUser1'
password = 'Hola2025'
driver = '{ODBC Driver 17 for SQL Server}'
conn = pyodbc.connect(
    f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;'
)
cur = conn.cursor()

## Ejercicios

### 1. Lista ProductID, Name, ListPrice de SalesLT.Product
(SELECT)

In [145]:
respuesta1 = pd.read_sql_query("SELECT ProductID, Name, ListPrice FROM SalesLT.Product", conn)
respuesta1

/tmp/ipython-input-3065315664.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  respuesta1 = pd.read_sql_query("SELECT ProductID, Name, ListPrice FROM SalesLT.Product", conn)

     ProductID                       Name  ListPrice
0          680  HL Road Frame - Black, 58    1431.50
1          706    HL Road Frame - Red, 58    1431.50
2          707      Sport-100 Helmet, Red      34.99
3          708    Sport-100 Helmet, Black      34.99
4          709     Mountain Bike Socks, M       9.50
..         ...                        ...        ...
290        995          ML Bottom Bracket     101.24
291        996          HL Bottom Bracket     121.49
292        997         Road-750 Black, 44     539.99
293        998         Road-750 Black, 48     539.99
294        999         Road-750 Black, 52     539.99

[295 rows x 3 columns]

### 2. Devuelve productos con ListPrice > 1000 mostrando ProductNumber, Name, ListPrice.
(Recuerda usar WHERE)

In [146]:
respuesta2 = pd.read_sql_query("SELECT ProductID, Name, ListPrice FROM SalesLT.Product where ListPrice > 1000 ", conn)
respuesta2

/tmp/ipython-input-2144609257.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  respuesta2 = pd.read_sql_query("SELECT ProductID, Name, ListPrice FROM SalesLT.Product where ListPrice > 1000 ", conn)

    ProductID                       Name  ListPrice
0         680  HL Road Frame - Black, 58    1431.50
1         706    HL Road Frame - Red, 58    1431.50
2         717    HL Road Frame - Red, 62    1431.50
3         718    HL Road Frame - Red, 44    1431.50
4         719    HL Road Frame - Red, 48    1431.50
..        ...                        ...        ...
81        972      Touring-2000 Blue, 54    1214.85
82        973      Road-350-W Yellow, 40    1700.99
83        974      Road-350-W Yellow, 42    1700.99
84        975      Road-350-W Yellow, 44    1700.99
85        976      Road-350-W Yellow, 48    1700.99

[86 rows x 3 columns]

### 3. Muestra el TOP 5 productos más caros con ProductID, Name, ListPrice.

In [147]:
respuesta3 = pd.read_sql_query("SELECT TOP 5 ProductID, Name, ListPrice FROM SalesLT.Product", conn)
respuesta3

/tmp/ipython-input-420304794.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  respuesta3 = pd.read_sql_query("SELECT TOP 5 ProductID, Name, ListPrice FROM SalesLT.Product", conn)

   ProductID                       Name  ListPrice
0        680  HL Road Frame - Black, 58    1431.50
1        706    HL Road Frame - Red, 58    1431.50
2        707      Sport-100 Helmet, Red      34.99
3        708    Sport-100 Helmet, Black      34.99
4        709     Mountain Bike Socks, M       9.50

### 4. Lista ProductID, p.Name AS ProductName, c.Name AS CategoryName para productos con categoría
(INNER JOIN).

In [148]:
query = """
SELECT
    p.ProductID,
    p.Name AS ProductName,
    c.Name AS CategoryName
FROM SalesLT.Product p
INNER JOIN SalesLT.ProductCategory c
    ON p.ProductCategoryID = c.ProductCategoryID
"""

respuesta = pd.read_sql_query(query, conn)
respuesta

/tmp/ipython-input-2252199751.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  respuesta = pd.read_sql_query(query, conn)

     ProductID              ProductName     CategoryName
0          771  Mountain-100 Silver, 38   Mountain Bikes
1          772  Mountain-100 Silver, 42   Mountain Bikes
2          773  Mountain-100 Silver, 44   Mountain Bikes
3          774  Mountain-100 Silver, 48   Mountain Bikes
4          775   Mountain-100 Black, 38   Mountain Bikes
..         ...                      ...              ...
290        930         HL Mountain Tire  Tires and Tubes
291        931             LL Road Tire  Tires and Tubes
292        932             ML Road Tire  Tires and Tubes
293        933             HL Road Tire  Tires and Tubes
294        934             Touring Tire  Tires and Tubes

[295 rows x 3 columns]

### 5. Obtén pedidos del año 2008 en adelante (o el año que aplique en tu base) con SalesOrderID, OrderDate, CustomerID, TotalDue y el nombre del cliente (FirstName + ' ' + LastName).
(JOIN + WHERE)

In [149]:
query = """
SELECT
    so.SalesOrderID,
    so.OrderDate,
    so.CustomerID,
    so.TotalDue,
    (c.FirstName + ' ' + c.LastName) AS CustomerName
FROM SalesLT.SalesOrderHeader AS so
INNER JOIN SalesLT.Customer AS c
    ON so.CustomerID = c.CustomerID
WHERE YEAR(so.OrderDate) >= 2008;
"""

respuesta5 = pd.read_sql_query(query, conn)
respuesta5

/tmp/ipython-input-1511307739.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  respuesta5 = pd.read_sql_query(query, conn)

    SalesOrderID  OrderDate  CustomerID     TotalDue          CustomerName
0          71782 2008-06-01       29485   43962.7901        Catherine Abel
1          71935 2008-06-01       29531    7330.8972            Cory Booth
2          71938 2008-06-01       29546   98138.2131      Christopher Beck
3          71899 2008-06-01       29568    2669.3183        Donald Blanton
4          71895 2008-06-01       29584     272.6468          Walter Brian
5          71885 2008-06-01       29612     608.1766         Richard Byham
6          71915 2008-06-01       29638    2361.6403      Rosmarie Carroll
7          71867 2008-06-01       29644    1170.5376      Brigid Cavendish
8          71858 2008-06-01       29653   15275.1977              Pei Chow
9          71796 2008-06-01       29660   63686.2708          Anthony Chor
10         71784 2008-06-01       29736  119960.8240       Terry Eminhizer
11         71946 2008-06-01       29741      43.0437        Janeth Esteves
12         71923 2008-06-01       29781     117.7276           Guy Gilbert
13         71797 2008-06-01       29796   86222.8072            Jon Grande
14         71774 2008-06-01       29847     972.7850         David Hodgson
15         71897 2008-06-01       29877   14017.9083          Joyce Jarvis
16         71832 2008-06-01       29922   39531.6085           Pamala Kotc
17         71902 2008-06-01       29929   81834.9826         Jeffrey Kurtz
18         71898 2008-06-01       29932   70698.9922        Rebecca Laszlo
19         71845 2008-06-01       29938   45992.3665        Frank Campbell
20         71783 2008-06-01       29957   92663.5609             Kevin Liu
21         71863 2008-06-01       29975    3673.3249           Walter Mays
22         71920 2008-06-01       29982    3293.7761        Melissa Marple
23         71831 2008-06-01       30019    2228.0566        Matthew Miller
24         71917 2008-06-01       30025      45.1995        Linda Mitchell
25         71816 2008-06-01       30027    3754.9733        Joseph Mitzner
26         71856 2008-06-01       30033     665.4251          Vassar Stern
27         71936 2008-06-01       30050  108597.9536  Krishna Sunkammurali
28         71776 2008-06-01       30072      87.0851        Andrea Thomsen
29         71815 2008-06-01       30089    1261.4440   Michael John Troyer
30         71846 2008-06-01       30102    2711.4098      Roger Van Houten
31         71780 2008-06-01       30113   42452.6519        Raja Venugopal

### 6. Para cada ProductID, suma la cantidad vendida (SUM(OrderQty)). Devuelve solo productos con ventas totales > 1000, ordenados de manera descendente.
Usa GROUP BY, HAVING y ORDER BY

In [150]:
query = """
SELECT
    ProductID,
    SUM(OrderQty) AS TotalQuantitySold
FROM SalesLT.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(OrderQty) > 1000
ORDER BY TotalQuantitySold DESC;
"""

respuesta6 = pd.read_sql_query(query, conn)
respuesta6

/tmp/ipython-input-1065248998.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  respuesta6 = pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [ProductID, TotalQuantitySold]
Index: []

### 7. Productos sin ventas: lista productos que no aparecen en SalesLT.SalesOrderDetail.
Usa LEFT JOIN + WHERE

In [151]:
query = """
SELECT
    p.ProductID,
    p.Name AS ProductName
FROM SalesLT.Product AS p
LEFT JOIN SalesLT.SalesOrderDetail AS d
    ON p.ProductID = d.ProductID
WHERE d.ProductID IS NULL;
"""

productos_sin_ventas = pd.read_sql_query(query, conn)
productos_sin_ventas

/tmp/ipython-input-114716097.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  productos_sin_ventas = pd.read_sql_query(query, conn)

     ProductID              ProductName
0          879   All-Purpose Bike Stand
1          843               Cable Lock
2          866          Classic Vest, L
3          878    Fender Set - Mountain
4          863    Full-Finger Gloves, L
..         ...                      ...
148        923        Touring Tire Tube
149        842  Touring-Panniers, Large
150        854        Women's Tights, L
151        853        Women's Tights, M
152        852        Women's Tights, S

[153 rows x 2 columns]

### 8. Clientes por país: total de clientes por CountryRegion (usa Address + CustomerAddress).
Podrias necesitar: COUNT(DISTINCT CustomerID).

In [152]:
query = """
SELECT
    a.CountryRegion,
    COUNT(DISTINCT ca.CustomerID) AS TotalCustomers
FROM SalesLT.Address AS a
INNER JOIN SalesLT.CustomerAddress AS ca
    ON a.AddressID = ca.AddressID
GROUP BY a.CountryRegion
ORDER BY TotalCustomers DESC;
"""

clientes_por_pais = pd.read_sql_query(query, conn)
clientes_por_pais

/tmp/ipython-input-3867649943.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  clientes_por_pais = pd.read_sql_query(query, conn)

    CountryRegion  TotalCustomers
0   United States             263
1          Canada             106
2  United Kingdom              38

### 9. Ticket promedio por año: AVG(TotalDue) por YEAR(OrderDate).

In [153]:
query = """
SELECT
    YEAR(OrderDate) AS Year,
    AVG(TotalDue) AS AverageTicket
FROM SalesLT.SalesOrderHeader
GROUP BY YEAR(OrderDate)
ORDER BY Year;
"""

ticket_promedio = pd.read_sql_query(query, conn)
ticket_promedio

/tmp/ipython-input-781322018.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ticket_promedio = pd.read_sql_query(query, conn)

   Year  AverageTicket
0  2008     29884.4873